version: "3" 
services:
    web:
        # container_name: springboot-app
        image: springboot-app 
        depends_on:
            - db
        # expose:
        #     - "5000"    
        # ports:
        #     - 8080:8080        
        environment:
            MYSQL_HOST: mysqldb 
            MYSQL_PASSWORD: pwd1234
    db:
        container_name: mysqldb
        image: mysql
        ports:
            - 3306:3306
        volumes: 
            - C:\Users\mutha\Documents\mysqldb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: pwd1234
            MYSQL_DATABASE: mysqldb
    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - web
        ports:
            - "3000:3000"        